name: streetwise
description: A price comparison and navigation app for Nairobi
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Standard iOS-style icons
  cupertino_icons: ^1.0.8

  # Modern outlined icons
  iconsax: ^0.0.8

  # For hero image carousel
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hero/
    - assets/images/categories/
